# Práctica 2: Ejercicios propuestos
# Inteligencia Artificial
# Grado en Ingeniería Informática - Ingeniería del Software
# Universidad de Sevilla

Los ejercicios que se plantean a continuación tienen como objetivo el practicar con la biblioteca [Keras](https://keras.io/2.15/api/) de Python.

In [6]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

### Ejercicio 1

El hormigón es el material más importante en la ingeniería civil. La resistencia a la compresión del hormigón es una función altamente no lineal de su edad y sus ingredientes.

El fichero `concrete_data.csv` contiene la siguiente información acerca de diferentes muestras de hormigón:

* Contenido de cemento (`Cement`).
* Contenido de escoria de alto horno (`Blast Furnace Slag`).
* Contenido de cenizas volantes (`Fly Ash`).
* Contenido de agua (`Water`).
* Contenido de superplastificantes (`Superplasticizer`).
* Contenido de agregados gruesos (`Coarse Aggregate`).
* Contenido de agregados finos (`Fine Aggregate`).
* Edad del hormigón (`Age`).

El objetivo es predecir la resistencia a la compresión (`Strength`) a partir de esos atributos continuos.

Se pide realizar lo siguiente:

1. Dividir el conjunto de datos en un subconjunto de entrenamiento y un subconjunto de prueba.
2. Abordar la tarea mediante una red neuronal que tenga una única capa oculta con 16 neuronas y función de activación sigmoide.
3. Entrenar la red durante 50 épocas, usando el error cuadrático medio como función de coste a minimizar.
4. Calcular el rendimiento de la red como el error absoluto medio sobre el conjunto de prueba.
5. Experimentar con distintas arquitecturas de la red (cantidad de capas ocultas, cantidad de neuronas en cada capa oculta, función de activación de las capas) e hiperparámetros de entrenamiento (factor de aprendizaje, tamaño de los minilotes, número de épocas), tratando de encontrar una red con un error absoluto medio sobre el conjunto de prueba menor a 0.1.

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

from keras.utils import set_random_seed

set_random_seed(5470)

import pandas as pd

data = pd.read_csv('concrete_data.csv')
data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [10]:
# 1. Dividir en subconjunto de entrenamiento y prueba
from sklearn.model_selection import train_test_split
atributos = data.loc[:,'Cement':'Age']
objetivo = data.loc[:,'Strength']


(atributos_train, atributos_test, 
 objetivo_train, objetivo_test) = train_test_split(atributos, objetivo, test_size=.2)

In [12]:
# Antes de Abordar el punto 2. Normalizamos los datos.
from keras.layers import Normalization
import numpy as np

normalizador = Normalization()
normalizador.adapt(atributos_train.to_numpy())

np.mean(normalizador(atributos_train), axis=0)

array([-4.28001492e-08,  5.96046448e-08,  2.18453913e-08,  1.18883776e-07,
       -2.11220339e-08, -1.75183587e-07,  1.62321385e-07,  3.61678665e-09],
      dtype=float32)

In [ ]:
# Comprobar la normalización -> media y varianza con valores entre 0 y 1
np.var(normalizador(atributos_train), axis = 0)
np.me

array([1.0000007 , 1.0000027 , 1.0000027 , 0.9999988 , 0.99999726,
       1.0000011 , 0.99999994, 0.99999857], dtype=float32)

In [15]:
# 2. Abordar la tarea mediante una red neuronal que tenga una única capa oculta con 16 neuronas
#  y función de activación sigmoide.

from keras import Sequential, Input
from keras.layers import Dense


neuronal_network = Sequential()
neuronal_network.add(Input(shape=(8,)))
neuronal_network.add(normalizador)
neuronal_network.add(Dense(16,activation='sigmoid'))
neuronal_network.add(Dense(1))

neuronal_network.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ normalization_3 (Normalization) │ (None, 8)              │            17 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 178 (716.00 B)

 Trainable params: 161 (644.00 B)

 Non-trainable params: 17 (72.00 B)

In [16]:
# 3. Entrenar la red durante 50 épocas, usando el error cuadrático medio como función de coste a minimizar.

neuronal_network.compile(optimizer='SGD',loss='mean_squared_error', metrics= ['mean_absolute_error'])
neuronal_network.fit(atributos_train, objetivo_train, batch_size=256, epochs=50)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 1355.3864 - mean_absolute_error: 32.4850
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 633.0291 - mean_absolute_error: 20.2345
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 285.1031 - mean_absolute_error: 13.1621
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 182.8779 - mean_absolute_error: 10.6471
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 146.9384 - mean_absolute_error: 9.6658
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 128.4306 - mean_absolute_error: 9.1024
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 117.6032 - mean_absolute_error: 8.7110
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 110.7386 - mean_absolute_error: 8.4205
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 105.9995 - mean_absolute_error: 8.1978
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 102.4558 - mean_absolute_error: 8.0095
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 99.6276 - mean_absolute_error: 7.8536
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 97.2579 - mean_absolute_error: 7.7261
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 95.2016 - mean_absolute_error: 7.6190
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 93.3720 - mean_absolute_error: 7.5272
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 91.7129 - mean_absolute_error: 7.4430
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 90.1859 - mean_absolute_error: 7.3656
Epoch 17/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 88.7651 - mean_absolute_error: 7.2942
Epoch 18/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 87.4356 - mean_absolute_error: 7.2295
Epoch 19/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 86.1915 - mean_absolute_error: 7.1687
Epoch 20/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.0305 - mean_absolute_error: 7.1133
Epoch 21/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 83.9470 - mean_absolute_error: 7.0642
Epoch 22/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 82.9309 - mean_absolute_error: 7.0199
Epoch 23/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 81.9705 - mean_absolute_error: 6.9790
Epoch 24/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 81.0580 - mean_absolute_error: 6.9410
Epoch 25/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.1917 - mean_absolute_error: 6.9049
Epoch 26/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 79.3720 - mean_absolute_error: 6.8706
Epoch 27/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.5966 - mean_absolute_error: 6.8378
Epoch 28/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 77.8586 - mean_absolute_error: 6.8068
Epoch 29/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 77.1476 - mean_absolute_error: 6.7772
Epoch 30/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 76.4515 - mean_absolute_error: 6.7482
Epoch 31/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 75.7569 - mean_absolute_error: 6.7204
Epoch 32/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 75.0501 - mean_absolute_error: 6.6923
Epoch 33/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 74.3185 - mean_absolute_error: 6.6631
Epoch 34/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 73.5580 - mean_absolute_error: 6.6332
Epoch 35/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 72.7857 - mean_absolute_error: 6.6028
Epoch 36/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 72.0410 - mean_absolute_error: 6.5739
Epoch 37/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 71.3597 - mean_absolute_error: 6.5459
Epoch 38/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 70.7486 - mean_absolute_error: 6.5192
Epoch 39/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.1942 - mean_absolute_error: 6.4941
Epoch 40/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 69.6802 - mean_absolute_error: 6.4703
Epoch 41/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 69.1945 - mean_absolute_error: 6.4476
Epoch 42/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68.7289 - mean_absolute_error: 6.4263
Epoch 43/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 68.2775 - mean_absolute_error: 6.4055
Epoch 44/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 67.8366 - mean_absolute_error: 6.3850
Epoch 45/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 67.4032 - mean_absolute_error: 6.3649
Epoch 46/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 66.9748 - mean_absolute_error: 6.3451
Epoch 47/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 66.5497 - mean_absolute_error: 6.3259
Epoch 48/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 66.1264 - mean_absolute_error: 6.3068
Epoch 49/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 65.7041 - mean_absolute_error: 6.2879
Epoch 50/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 65.2824 - mean_absolute_error: 6.2691

In [17]:
# 4. Calcular el rendimiento de la red como el error absoluto medio sobre el conjunto de prueba.

loss, mae = neuronal_network.evaluate(atributos_test, objetivo_test)
print("MSE (loss):", loss)
print("MAE:", mae)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 64.0627 - mean_absolute_error: 6.2642
MSE (loss): 64.06268310546875
MAE: 6.264230251312256

In [18]:
# 5. Experimentar con distintas arquitecturas de la red (cantidad de capas ocultas, cantidad de neuronas en cada capa 
# oculta, función de activación de las capas) e hiperparámetros de entrenamiento 
# (factor de aprendizaje, tamaño de los minilotes, número de épocas), 
# tratando de encontrar una red con un error absoluto medio sobre el conjunto de prueba menor a 0.1.

# cambio en el factor de aprendizaje
from keras.optimizers import SGD

neuronal_network = Sequential()
neuronal_network.add(Input(shape=(8,)))
neuronal_network.add(normalizador)
neuronal_network.add(Dense(32,activation='sigmoid'))
neuronal_network.add(Dense(16,activation='sigmoid'))
neuronal_network.add(Dense(16,activation='sigmoid'))
neuronal_network.add(Dense(16,activation='sigmoid'))
neuronal_network.add(Dense(1))

compile = neuronal_network.compile(
    optimizer=SGD(learning_rate=0.001),
    loss='mean_squared_error',
    metrics= ['mean_absolute_error'])
neuronal_network.fit(atributos_train, objetivo_train, batch_size=256, epochs=100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1543.8768 - mean_absolute_error: 35.4853
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1428.8527 - mean_absolute_error: 33.8261
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1315.5834 - mean_absolute_error: 32.1137
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1201.7607 - mean_absolute_error: 30.3017
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1088.4839 - mean_absolute_error: 28.4064
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 978.6597 - mean_absolute_error: 26.4938
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 875.4844 - mean_absolute_error: 24.6429
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 781.4421 - mean_absolute_error: 22.9271
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 697.9365 - mean_absolute_error: 21.3835
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 625.3526 - mean_absolute_error: 20.0408
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 563.3255 - mean_absolute_error: 18.8708
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 511.0406 - mean_absolute_error: 17.8363
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 467.4669 - mean_absolute_error: 16.9544
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 431.5032 - mean_absolute_error: 16.2163
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 402.0653 - mean_absolute_error: 15.6336
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 378.1379 - mean_absolute_error: 15.1852
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 358.8039 - mean_absolute_error: 14.8236
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 343.2587 - mean_absolute_error: 14.5240
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 330.8115 - mean_absolute_error: 14.2733
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 320.8800 - mean_absolute_error: 14.0713
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 312.9795 - mean_absolute_error: 13.9160
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 306.7113 - mean_absolute_error: 13.7873
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 301.7499 - mean_absolute_error: 13.6883
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 297.8315 - mean_absolute_error: 13.6150
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 294.7433 - mean_absolute_error: 13.5591
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 292.3143 - mean_absolute_error: 13.5225
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 290.4076 - mean_absolute_error: 13.5009
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 288.9142 - mean_absolute_error: 13.4909
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 287.7471 - mean_absolute_error: 13.4875
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 286.8372 - mean_absolute_error: 13.4859
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 286.1297 - mean_absolute_error: 13.4853
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 285.5811 - mean_absolute_error: 13.4863
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 285.1572 - mean_absolute_error: 13.4880
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 284.8309 - mean_absolute_error: 13.4902
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 284.5808 - mean_absolute_error: 13.4931
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 284.3900 - mean_absolute_error: 13.4970
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 284.2454 - mean_absolute_error: 13.5008
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 284.1366 - mean_absolute_error: 13.5042
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 284.0553 - mean_absolute_error: 13.5072
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.9953 - mean_absolute_error: 13.5102
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 283.9516 - mean_absolute_error: 13.5130
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.9203 - mean_absolute_error: 13.5158
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8983 - mean_absolute_error: 13.5184
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8834 - mean_absolute_error: 13.5207
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8737 - mean_absolute_error: 13.5227
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8679 - mean_absolute_error: 13.5246
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 283.8648 - mean_absolute_error: 13.5263
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 283.8636 - mean_absolute_error: 13.5278
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 283.8639 - mean_absolute_error: 13.5291
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 283.8650 - mean_absolute_error: 13.5303
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 283.8666 - mean_absolute_error: 13.5313
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8685 - mean_absolute_error: 13.5323
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 283.8705 - mean_absolute_error: 13.5332
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8725 - mean_absolute_error: 13.5340
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8743 - mean_absolute_error: 13.5347
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8759 - mean_absolute_error: 13.5353
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8773 - mean_absolute_error: 13.5359
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8784 - mean_absolute_error: 13.5364
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8792 - mean_absolute_error: 13.5368
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8798 - mean_absolute_error: 13.5372
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 283.8801 - mean_absolute_error: 13.5375
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 283.8802 - mean_absolute_error: 13.5378
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8800 - mean_absolute_error: 13.5381
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8796 - mean_absolute_error: 13.5383
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8790 - mean_absolute_error: 13.5385
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 283.8782 - mean_absolute_error: 13.5387
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 283.8772 - mean_absolute_error: 13.5388
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 283.8761 - mean_absolute_error: 13.5389
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 283.8748 - mean_absolute_error: 13.5390
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8734 - mean_absolute_error: 13.5391
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8719 - mean_absolute_error: 13.5391
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8703 - mean_absolute_error: 13.5392
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8685 - mean_absolute_error: 13.5392
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 283.8667 - mean_absolute_error: 13.5392
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8647 - mean_absolute_error: 13.5393
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8628 - mean_absolute_error: 13.5393
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 283.8607 - mean_absolute_error: 13.5393
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 283.8586 - mean_absolute_error: 13.5392
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8564 - mean_absolute_error: 13.5392
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8542 - mean_absolute_error: 13.5392
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8520 - mean_absolute_error: 13.5392
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8497 - mean_absolute_error: 13.5392
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8474 - mean_absolute_error: 13.5391
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 283.8450 - mean_absolute_error: 13.5391
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 283.8426 - mean_absolute_error: 13.5391
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 283.8402 - mean_absolute_error: 13.5390
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8378 - mean_absolute_error: 13.5390
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 283.8353 - mean_absolute_error: 13.5389
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 283.8329 - mean_absolute_error: 13.5389
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8304 - mean_absolute_error: 13.5388
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8278 - mean_absolute_error: 13.5388
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 283.8253 - mean_absolute_error: 13.5387
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8228 - mean_absolute_error: 13.5387
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8202 - mean_absolute_error: 13.5386
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8176 - mean_absolute_error: 13.5385
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 283.8150 - mean_absolute_error: 13.5385
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.8125 - mean_absolute_error: 13.5384
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 283.8099 - mean_absolute_error: 13.5384
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 283.8073 - mean_absolute_error: 13.5383
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 283.8047 - mean_absolute_error: 13.5382

### Ejercicio 2

El fichero `cars.csv` contiene información acerca de la idoneidad de una serie de coches, en función de los siguientes atributos discretos:

* Precio de compra (`buying`): posibles valores `vhigh`, `high`, `med`, `low`.
* Coste de mantenimiento (`maint`): posibles valores `vhigh`, `high`, `med`, `low`.
* Número de puertas (`doors`): posibles valores `2`, `3`, `4`, `5more`.
* Número de asientos (`persons`): posibles valores `2`, `4`, `more`.
* Tamaño del maletero (`lug_boot`): posibles valores `small`, `med`, `big`.
* Nivel de seguridad estimada (`safety`): posibles valores `low`, `med`, `high`.

La idoneidad de cada coche se indica mediante el atributo `acceptability`, que los clasifica como `unacc`, `acc`, `good` o `vgood`.

Se pide realizar lo siguiente:

1. Dividir el conjunto de datos en un subconjunto de entrenamiento y un subconjunto de prueba.
2. Abordar la tarea mediante una red neuronal que tenga una única capa oculta con 16 neuronas y función de activación tangente hiperbólica.
3. Entrenar la red durante 50 épocas, usando la entropía cruzada categórica como función de coste a minimizar.
4. Calcular el rendimiento de la red como la tasa de acierto sobre el conjunto de prueba.
5. Experimentar con distintas arquitecturas de la red (cantidad de capas ocultas, cantidad de neuronas en cada capa oculta, función de activación de las capas) e hiperparámetros de entrenamiento (factor de aprendizaje, tamaño de los minilotes), tratando de encontrar una red que, entrenada únicamente durante 50 épocas, tenga una tasa de acierto sobre el conjunto de prueba superior a 0.9.

In [19]:
# leemos los datos
import pandas as pf

datos = pd.read_csv('cars.csv')
# mostramos las primeras lineas
datos.head()

  buying  maint doors persons lug_boot safety acceptability
0  vhigh  vhigh     2       2    small    low         unacc
1  vhigh  vhigh     2       2    small    med         unacc
2  vhigh  vhigh     2       2    small   high         unacc
3  vhigh  vhigh     2       2      med    low         unacc
4  vhigh  vhigh     2       2      med    med         unacc

In [ ]:
# 1. Dividir el conjunto de datos en un subconjunto de entrenamiento y un subconjunto de prueba.
atributos_entrenamiento = datos.loc[:,'buying':'safety']
atributos_objetivo = datos.loc[:,'acceptability':'acceptability']
atributos_objetivo.head()

InvalidIndexError: (slice(None, None, None), slice('acceptability', 'acceptability', None))

### Ejercicio 3

Los púlsares son un tipo raro de estrella de neutrones que produce emisiones de radio detectables aquí en la Tierra. Son de considerable interés científico como sondas del espacio-tiempo, el medio interestelar y los estados de la materia.

A medida que los púlsares giran, su haz de emisión recorre el cielo y, cuando cruza nuestra línea de visión, produce un patrón detectable de emisión de radio de banda ancha. Como los púlsares giran rápidamente, este patrón se repite periódicamente. Por tanto, la búsqueda de púlsares implica buscar señales de radio periódicas con grandes radiotelescopios.

Cada púlsar produce un patrón de emisión algo diferente, que varía levemente con cada rotación. Por lo tanto, una detección de señal potencial conocida como «candidata» se promedia a lo largo de muchas rotaciones del púlsar, según lo determinado por la duración de una observación. A falta de información adicional, cada candidato podría describir un púlsar real. Sin embargo, en la práctica, casi todas las detecciones son causadas por interferencias de radiofrecuencia (RFI) y ruido, lo que dificulta encontrar señales legítimas.

El fichero `pulsar_stars.csv` contiene datos acerca de una serie de púlsares reales y de ejemplos espurios producidos por RFI y ruido. Cada candidato se describe mediante ocho atributos continuos extraídos de las señales recibidas.

Se pide construir una red neuronal que permita abordar, con el mayor rendimiento posible, la tarea de de determinar si un candidato es o no un púlsar.

### Ejercicio 4

Los [abulones](https://es.wikipedia.org/wiki/Haliotis) son una familia de moluscos gasterópodos. La edad de cada individuo está correlacionada con el número de anillos de su concha y, por tanto, puede determinarse cortando la concha a través del cono, tiñéndola y contando el número de anillos a través de un microscopio. Este procedimiento requiere mucho tiempo y es propenso a errores, por lo que sería preferible poder determinar la edad directamente a partir de medidas físicas más fáciles de obtener.

El fichero `abalone.csv` contiene la siguiente información de distintos individuos de abulones:

* Sexo (`Sex`): atributo discreto con posibles valores `M` (macho), `F` (hembra) e `I` (infante).
* Longitud (`Length`) en milímetros.
* Diámetro (`Diameter`) en milímetros.
* Altura (`Height`) en milímetros.
* Peso total (`Whole_weight`) en gramos.
* Peso sin la concha (`Shucked_weight`) en gramos.
* Peso intestinal (`Viscera_weight`) en gramos.
* Peso de la concha (`Shell_weight`) en gramos.

Se pide construir una red neuronal que permita abordar, con el mayor rendimiento posible, la tarea de predecir el número de anillos (`Rings`) a partir de los atributos anteriores (entonces bastaría sumar 1.5 a ese número de anillos para obtener la edad, en años, del individuo).