# Práctica 2: Soluciones de los ejercicios propuestos
# Inteligencia Artificial
# Grado en Ingeniería Informática - Ingeniería del Software
# Universidad de Sevilla

Los ejercicios que se plantean a continuación tienen como objetivo el practicar con la biblioteca [Keras](https://keras.io/api/) de Python.

In [146]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

### Ejercicio 1

El hormigón es el material más importante en la ingeniería civil. La resistencia a la compresión del hormigón es una función altamente no lineal de su edad y sus ingredientes.

El fichero `concrete_data.csv` contiene la siguiente información acerca de diferentes muestras de hormigón:

* Contenido de cemento (`Cement`).
* Contenido de escoria de alto horno (`Blast Furnace Slag`).
* Contenido de cenizas volantes (`Fly Ash`).
* Contenido de agua (`Water`).
* Contenido de superplastificantes (`Superplasticizer`).
* Contenido de agregados gruesos (`Coarse Aggregate`).
* Contenido de agregados finos (`Fine Aggregate`).
* Edad del hormigón (`Age`).

El objetivo es predecir la resistencia a la compresión (`Strength`) a partir de esos atributos continuos.

Se pide realizar lo siguiente:

1. Dividir el conjunto de datos en un subconjunto de entrenamiento y un subconjunto de prueba.
2. Abordar la tarea mediante una red neuronal que tenga una única capa oculta con 16 neuronas y función de activación sigmoide.
3. Entrenar la red durante 50 épocas, usando el error cuadrático medio como función de coste a minimizar.
4. Calcular el rendimiento de la red como el error absoluto medio sobre el conjunto de prueba.
5. Experimentar con distintas arquitecturas de la red (cantidad de capas ocultas, cantidad de neuronas en cada capa oculta, función de activación de las capas) e hiperparámetros de entrenamiento (factor de aprendizaje, tamaño de los minilotes, número de épocas), tratando de encontrar una red con un error absoluto medio sobre el conjunto de prueba menor a 0.1.

In [147]:
import os
#os.environ["KERAS_BACKEND"] = "torch"

from keras.utils import set_random_seed

set_random_seed(982375)

In [148]:
import pandas as pd

In [149]:
hormigón = pd.read_csv('concrete_data.csv')
hormigón.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [150]:
hormigón.shape

(1030, 9)

In [151]:
hormigón.isna().any()

Cement                False
Blast Furnace Slag    False
Fly Ash               False
Water                 False
Superplasticizer      False
Coarse Aggregate      False
Fine Aggregate        False
Age                   False
Strength              False
dtype: bool

In [152]:
atributos = hormigón.loc[:, 'Cement':'Age']
atributos.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [153]:
objetivo = hormigón.loc[:, ['Strength']]
objetivo.head()

   Strength
0     79.99
1     61.89
2     40.27
3     41.05
4     44.30

In [154]:
from sklearn.model_selection import train_test_split

In [155]:
(atributos_entrenamiento, atributos_prueba,
 objetivo_entrenamiento, objetivo_prueba) = train_test_split(
    atributos, objetivo,
    test_size=.2
)

In [156]:
from keras import Sequential, Input
from keras.layers import Dense, Normalization

In [157]:
normalizador = Normalization()
normalizador.adapt(atributos_entrenamiento.to_numpy())

Tomado de https://community.deeplearning.ai/t/doubt-about-relu-activation-in-hidden-layer/264792.


![Alt text](https://global.discourse-cdn.com/dlai/original/3X/d/4/d410f436378cd5af1ded43d0f4209bc3a5437e49.jpeg)

In [ ]:
red_hormigón = Sequential()
red_hormigón.add(Input(shape=(8,)))
red_hormigón.add(normalizador)
red_hormigón.add(Dense(16, activation='sigmoid'))
red_hormigón.add(Dense(1))

In [159]:
red_hormigón.compile(optimizer='SGD', loss='mean_squared_error',
                     metrics=['mean_absolute_error'])

In [160]:
red_hormigón.fit(atributos_entrenamiento, objetivo_entrenamiento,
                 batch_size=256, epochs=700)

Epoch 1/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1333.4763 - mean_absolute_error: 32.2738
Epoch 2/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 653.8478 - mean_absolute_error: 20.5382
Epoch 3/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 301.4130 - mean_absolute_error: 13.5175
Epoch 4/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 191.0023 - mean_absolute_error: 10.7924
Epoch 5/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 151.9274 - mean_absolute_error: 9.6875
Epoch 6/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 131.4752 - mean_absolute_error: 9.0482
Epoch 7/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 119.2835 - mean_absolute_error: 8.6168
Epoch 8/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 111.5251 - mean_absolute_error: 8.3127
Epoch 9/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.2366 - mean_absolute_error: 8.0804
Epoch 10/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 102.3770 - mean_absolute_error: 7.8941
Epoch 11/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 99.3871 - mean_absolute_error: 7.7458
Epoch 12/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 96.9578 - mean_absolute_error: 7.6207
Epoch 13/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 94.9134 - mean_absolute_error: 7.5145
Epoch 14/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.1513 - mean_absolute_error: 7.4235
Epoch 15/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.6084 - mean_absolute_error: 7.3406
Epoch 16/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.2407 - mean_absolute_error: 7.2660
Epoch 17/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.0125 - mean_absolute_error: 7.2008
Epoch 18/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 87.8933 - mean_absolute_error: 7.1451
Epoch 19/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 86.8567 - mean_absolute_error: 7.0945
Epoch 20/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.8809 - mean_absolute_error: 7.0480
Epoch 21/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 84.9482 - mean_absolute_error: 7.0047
Epoch 22/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 84.0443 - mean_absolute_error: 6.9651
Epoch 23/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 83.1589 - mean_absolute_error: 6.9279
Epoch 24/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 82.2855 - mean_absolute_error: 6.8936
Epoch 25/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.4212 - mean_absolute_error: 6.8606
Epoch 26/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.5628 - mean_absolute_error: 6.8282
Epoch 27/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.7059 - mean_absolute_error: 6.7974
Epoch 28/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.8483 - mean_absolute_error: 6.7666
Epoch 29/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.9935 - mean_absolute_error: 6.7364
Epoch 30/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.1473 - mean_absolute_error: 6.7065
Epoch 31/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 76.3129 - mean_absolute_error: 6.6769
Epoch 32/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 75.4909 - mean_absolute_error: 6.6474
Epoch 33/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 74.6852 - mean_absolute_error: 6.6180
Epoch 34/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 73.9060 - mean_absolute_error: 6.5898
Epoch 35/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 73.1634 - mean_absolute_error: 6.5630
Epoch 36/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.4599 - mean_absolute_error: 6.5367
Epoch 37/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.7908 - mean_absolute_error: 6.5112
Epoch 38/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.1487 - mean_absolute_error: 6.4863
Epoch 39/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 70.5266 - mean_absolute_error: 6.4621
Epoch 40/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.9192 - mean_absolute_error: 6.4385
Epoch 41/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.3223 - mean_absolute_error: 6.4158
Epoch 42/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.7327 - mean_absolute_error: 6.3935
Epoch 43/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.1479 - mean_absolute_error: 6.3713
Epoch 44/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 67.5660 - mean_absolute_error: 6.3491
Epoch 45/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.9857 - mean_absolute_error: 6.3271
Epoch 46/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 66.4072 - mean_absolute_error: 6.3060
Epoch 47/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 65.8324 - mean_absolute_error: 6.2852
Epoch 48/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 65.2652 - mean_absolute_error: 6.2645
Epoch 49/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.7113 - mean_absolute_error: 6.2440
Epoch 50/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.1763 - mean_absolute_error: 6.2238
Epoch 51/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.6637 - mean_absolute_error: 6.2043
Epoch 52/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1750 - mean_absolute_error: 6.1853
Epoch 53/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.7090 - mean_absolute_error: 6.1666
Epoch 54/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.2641 - mean_absolute_error: 6.1483
Epoch 55/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.8383 - mean_absolute_error: 6.1303
Epoch 56/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.4301 - mean_absolute_error: 6.1124
Epoch 57/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.0387 - mean_absolute_error: 6.0947
Epoch 58/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.6636 - mean_absolute_error: 6.0775
Epoch 59/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.3045 - mean_absolute_error: 6.0608
Epoch 60/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.9607 - mean_absolute_error: 6.0448
Epoch 61/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.6313 - mean_absolute_error: 6.0296
Epoch 62/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.3152 - mean_absolute_error: 6.0149
Epoch 63/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.0110 - mean_absolute_error: 6.0006
Epoch 64/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.7174 - mean_absolute_error: 5.9866
Epoch 65/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.4332 - mean_absolute_error: 5.9729
Epoch 66/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.1572 - mean_absolute_error: 5.9596
Epoch 67/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.8884 - mean_absolute_error: 5.9465
Epoch 68/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.6261 - mean_absolute_error: 5.9336
Epoch 69/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.3695 - mean_absolute_error: 5.9210
Epoch 70/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.1183 - mean_absolute_error: 5.9088
Epoch 71/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.8720 - mean_absolute_error: 5.8966
Epoch 72/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.6305 - mean_absolute_error: 5.8845
Epoch 73/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.3936 - mean_absolute_error: 5.8727
Epoch 74/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.1612 - mean_absolute_error: 5.8611
Epoch 75/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.9332 - mean_absolute_error: 5.8495
Epoch 76/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.7095 - mean_absolute_error: 5.8379
Epoch 77/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.4900 - mean_absolute_error: 5.8265
Epoch 78/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.2746 - mean_absolute_error: 5.8152
Epoch 79/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.0632 - mean_absolute_error: 5.8040
Epoch 80/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.8556 - mean_absolute_error: 5.7929
Epoch 81/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.6517 - mean_absolute_error: 5.7818
Epoch 82/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.4515 - mean_absolute_error: 5.7707
Epoch 83/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.2550 - mean_absolute_error: 5.7598
Epoch 84/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.0624 - mean_absolute_error: 5.7492
Epoch 85/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.8738 - mean_absolute_error: 5.7390
Epoch 86/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.6895 - mean_absolute_error: 5.7289
Epoch 87/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.5097 - mean_absolute_error: 5.7189
Epoch 88/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.3346 - mean_absolute_error: 5.7090
Epoch 89/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 53.1642 - mean_absolute_error: 5.6996
Epoch 90/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.9985 - mean_absolute_error: 5.6904
Epoch 91/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 52.8375 - mean_absolute_error: 5.6813
Epoch 92/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.6809 - mean_absolute_error: 5.6723
Epoch 93/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.5285 - mean_absolute_error: 5.6635
Epoch 94/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.3801 - mean_absolute_error: 5.6548
Epoch 95/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.2354 - mean_absolute_error: 5.6463
Epoch 96/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.0942 - mean_absolute_error: 5.6379
Epoch 97/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.9563 - mean_absolute_error: 5.6298
Epoch 98/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.8214 - mean_absolute_error: 5.6220
Epoch 99/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.6893 - mean_absolute_error: 5.6145
Epoch 100/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.5599 - mean_absolute_error: 5.6071
Epoch 101/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.4330 - mean_absolute_error: 5.5998
Epoch 102/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.3086 - mean_absolute_error: 5.5927
Epoch 103/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 51.1864 - mean_absolute_error: 5.5857
Epoch 104/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 51.0664 - mean_absolute_error: 5.5788
Epoch 105/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.9485 - mean_absolute_error: 5.5719
Epoch 106/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.8325 - mean_absolute_error: 5.5651
Epoch 107/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.7185 - mean_absolute_error: 5.5583
Epoch 108/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.6063 - mean_absolute_error: 5.5515
Epoch 109/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 50.4959 - mean_absolute_error: 5.5448
Epoch 110/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.3871 - mean_absolute_error: 5.5382
Epoch 111/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.2801 - mean_absolute_error: 5.5316
Epoch 112/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.1746 - mean_absolute_error: 5.5250
Epoch 113/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.0707 - mean_absolute_error: 5.5185
Epoch 114/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.9682 - mean_absolute_error: 5.5120
Epoch 115/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.8672 - mean_absolute_error: 5.5056
Epoch 116/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.7677 - mean_absolute_error: 5.4992
Epoch 117/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.6695 - mean_absolute_error: 5.4928
Epoch 118/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.5726 - mean_absolute_error: 5.4866
Epoch 119/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.4770 - mean_absolute_error: 5.4805
Epoch 120/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.3828 - mean_absolute_error: 5.4744
Epoch 121/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.2897 - mean_absolute_error: 5.4684
Epoch 122/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1978 - mean_absolute_error: 5.4625
Epoch 123/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1071 - mean_absolute_error: 5.4566
Epoch 124/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0175 - mean_absolute_error: 5.4509
Epoch 125/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 48.9290 - mean_absolute_error: 5.4452
Epoch 126/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8416 - mean_absolute_error: 5.4396
Epoch 127/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.7553 - mean_absolute_error: 5.4340
Epoch 128/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.6700 - mean_absolute_error: 5.4284
Epoch 129/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.5857 - mean_absolute_error: 5.4230
Epoch 130/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.5023 - mean_absolute_error: 5.4177
Epoch 131/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.4199 - mean_absolute_error: 5.4124
Epoch 132/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.3385 - mean_absolute_error: 5.4072
Epoch 133/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.2579 - mean_absolute_error: 5.4020
Epoch 134/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.1783 - mean_absolute_error: 5.3970
Epoch 135/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.0995 - mean_absolute_error: 5.3920
Epoch 136/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.0215 - mean_absolute_error: 5.3870
Epoch 137/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.9444 - mean_absolute_error: 5.3820
Epoch 138/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.8681 - mean_absolute_error: 5.3771
Epoch 139/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.7926 - mean_absolute_error: 5.3722
Epoch 140/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.7178 - mean_absolute_error: 5.3674
Epoch 141/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.6438 - mean_absolute_error: 5.3626
Epoch 142/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.5706 - mean_absolute_error: 5.3578
Epoch 143/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.4981 - mean_absolute_error: 5.3532
Epoch 144/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.4262 - mean_absolute_error: 5.3485
Epoch 145/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3551 - mean_absolute_error: 5.3439
Epoch 146/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.2846 - mean_absolute_error: 5.3394
Epoch 147/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.2148 - mean_absolute_error: 5.3349
Epoch 148/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.1457 - mean_absolute_error: 5.3305
Epoch 149/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.0772 - mean_absolute_error: 5.3260
Epoch 150/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.0093 - mean_absolute_error: 5.3217
Epoch 151/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.9420 - mean_absolute_error: 5.3173
Epoch 152/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.8753 - mean_absolute_error: 5.3130
Epoch 153/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.8092 - mean_absolute_error: 5.3088
Epoch 154/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.7437 - mean_absolute_error: 5.3046
Epoch 155/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.6787 - mean_absolute_error: 5.3004
Epoch 156/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.6142 - mean_absolute_error: 5.2962
Epoch 157/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.5504 - mean_absolute_error: 5.2920
Epoch 158/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.4870 - mean_absolute_error: 5.2878
Epoch 159/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 46.4241 - mean_absolute_error: 5.2837
Epoch 160/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.3618 - mean_absolute_error: 5.2797
Epoch 161/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.3000 - mean_absolute_error: 5.2757
Epoch 162/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.2386 - mean_absolute_error: 5.2717
Epoch 163/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 46.1777 - mean_absolute_error: 5.2678
Epoch 164/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 46.1173 - mean_absolute_error: 5.2638
Epoch 165/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 46.0574 - mean_absolute_error: 5.2599
Epoch 166/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.9979 - mean_absolute_error: 5.2560
Epoch 167/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.9388 - mean_absolute_error: 5.2521
Epoch 168/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.8802 - mean_absolute_error: 5.2483
Epoch 169/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.8220 - mean_absolute_error: 5.2445
Epoch 170/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.7642 - mean_absolute_error: 5.2408
Epoch 171/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.7069 - mean_absolute_error: 5.2371
Epoch 172/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.6499 - mean_absolute_error: 5.2334
Epoch 173/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.5933 - mean_absolute_error: 5.2298
Epoch 174/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.5372 - mean_absolute_error: 5.2262
Epoch 175/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.4814 - mean_absolute_error: 5.2226
Epoch 176/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.4260 - mean_absolute_error: 5.2190
Epoch 177/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.3709 - mean_absolute_error: 5.2155
Epoch 178/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.3162 - mean_absolute_error: 5.2121
Epoch 179/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.2619 - mean_absolute_error: 5.2087
Epoch 180/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.2079 - mean_absolute_error: 5.2054
Epoch 181/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 45.1543 - mean_absolute_error: 5.2020
Epoch 182/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.1010 - mean_absolute_error: 5.1987
Epoch 183/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45.0481 - mean_absolute_error: 5.1953
Epoch 184/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.9954 - mean_absolute_error: 5.1920
Epoch 185/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.9431 - mean_absolute_error: 5.1887
Epoch 186/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.8911 - mean_absolute_error: 5.1854
Epoch 187/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.8394 - mean_absolute_error: 5.1821
Epoch 188/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.7881 - mean_absolute_error: 5.1788
Epoch 189/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.7370 - mean_absolute_error: 5.1755
Epoch 190/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.6862 - mean_absolute_error: 5.1722
Epoch 191/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.6357 - mean_absolute_error: 5.1690
Epoch 192/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.5855 - mean_absolute_error: 5.1658
Epoch 193/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 44.5356 - mean_absolute_error: 5.1626
Epoch 194/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.4859 - mean_absolute_error: 5.1594
Epoch 195/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.4366 - mean_absolute_error: 5.1563
Epoch 196/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 44.3875 - mean_absolute_error: 5.1532
Epoch 197/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.3386 - mean_absolute_error: 5.1501
Epoch 198/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.2900 - mean_absolute_error: 5.1470
Epoch 199/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.2417 - mean_absolute_error: 5.1440
Epoch 200/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.1937 - mean_absolute_error: 5.1409
Epoch 201/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.1458 - mean_absolute_error: 5.1378
Epoch 202/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.0983 - mean_absolute_error: 5.1348
Epoch 203/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.0510 - mean_absolute_error: 5.1317
Epoch 204/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.0039 - mean_absolute_error: 5.1286
Epoch 205/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 43.9570 - mean_absolute_error: 5.1256
Epoch 206/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 43.9104 - mean_absolute_error: 5.1225
Epoch 207/700
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 43.8641 - mean_absolute_error: 5.1194
Epoch 208/700

In [161]:
red_hormigón.evaluate(atributos_prueba, objetivo_prueba)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.2067 - mean_absolute_error: 4.1458

[28.20671844482422, 4.1457600593566895]

In [162]:
from keras.optimizers import SGD

Funciones de activación comunes en las capas ocultas de las redes neuronales:

![Funciones de activacion](https://gkadusumilli.github.io/images/relu/activation_list.png)

In [163]:
red_hormigón = Sequential()
red_hormigón.add(Input(shape=(8,)))
red_hormigón.add(normalizador)
red_hormigón.add(Dense(4, activation='relu'))
red_hormigón.add(Dense(8, activation='relu'))
red_hormigón.add(Dense(1))

In [164]:
red_hormigón.compile(optimizer=SGD(learning_rate=0.0001), loss='mean_squared_error',
                     metrics=['mean_absolute_error'])

In [165]:
red_hormigón.fit(atributos_entrenamiento, objetivo_entrenamiento,
                 batch_size=64, epochs=300, verbose=False)

In [166]:
red_hormigón.evaluate(atributos_prueba, objetivo_prueba)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 96.0546 - mean_absolute_error: 8.0797

[96.05463409423828, 8.079695701599121]

### Ejercicio 2

El fichero `cars.csv` contiene información acerca de la idoneidad de una serie de coches, en función de los siguientes atributos discretos:

* Precio de compra (`buying`): posibles valores `vhigh`, `high`, `med`, `low`.
* Coste de mantenimiento (`maint`): posibles valores `vhigh`, `high`, `med`, `low`.
* Número de puertas (`doors`): posibles valores `2`, `3`, `4`, `5more`.
* Número de asientos (`persons`): posibles valores `2`, `4`, `more`.
* Tamaño del maletero (`lug_boot`): posibles valores `small`, `med`, `big`.
* Nivel de seguridad estimada (`safety`): posibles valores `low`, `med`, `high`.

La idoneidad de cada coche se indica mediante el atributo `acceptability`, que los clasifica como `unacc`, `acc`, `good` o `vgood`.

Se pide realizar lo siguiente:

1. Dividir el conjunto de datos en un subconjunto de entrenamiento y un subconjunto de prueba.
2. Abordar la tarea mediante una red neuronal que tenga una única capa oculta con 16 neuronas y función de activación tangente hiperbólica.
3. Entrenar la red durante 50 épocas, usando la entropía cruzada categórica como función de coste a minimizar.
4. Calcular el rendimiento de la red como la tasa de acierto sobre el conjunto de prueba.
5. Experimentar con distintas arquitecturas de la red (cantidad de capas ocultas, cantidad de neuronas en cada capa oculta, función de activación de las capas) e hiperparámetros de entrenamiento (factor de aprendizaje, tamaño de los minilotes), tratando de encontrar una red que, entrenada únicamente durante 50 épocas, tenga una tasa de acierto sobre el conjunto de prueba superior a 0.9.

In [167]:
from keras.utils import set_random_seed

set_random_seed(3752385)

In [168]:
import pandas as pd

In [169]:
coches = pd.read_csv('cars.csv')
coches.head()

  buying  maint doors persons lug_boot safety acceptability
0  vhigh  vhigh     2       2    small    low         unacc
1  vhigh  vhigh     2       2    small    med         unacc
2  vhigh  vhigh     2       2    small   high         unacc
3  vhigh  vhigh     2       2      med    low         unacc
4  vhigh  vhigh     2       2      med    med         unacc

In [170]:
coches.isna().any()

buying           False
maint            False
doors            False
persons          False
lug_boot         False
safety           False
acceptability    False
dtype: bool

In [171]:
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer

In [172]:
codificador_atributos = OneHotEncoder(sparse_output=False)
atributos = coches.loc[:, 'buying':'safety']
atributos = codificador_atributos.fit_transform(atributos)
atributos

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 0.]])

In [173]:
atributos.shape

(1728, 21)

In [174]:
codificador_objetivo = LabelBinarizer()
objetivo = coches['acceptability']
objetivo = codificador_objetivo.fit_transform(objetivo)
objetivo

array([[0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       ...,
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

In [175]:
from sklearn.model_selection import train_test_split

In [176]:
(atributos_entrenamiento, atributos_prueba,
 objetivo_entrenamiento, objetivo_prueba) = train_test_split(
    atributos, objetivo,
    test_size=.2
)

In [177]:
from keras import Sequential, Input
from keras.layers import Dense

¿Qué es posible obtener con softmax?

![Softmax](https://media.geeksforgeeks.org/wp-content/uploads/20240706012340/Softmax-Activation-Function.webp)

In [178]:
red_coches = Sequential()
red_coches.add(Input(shape=(21,)))
red_coches.add(Dense(16, activation='tanh'))
red_coches.add(Dense(4, activation='softmax'))

In [179]:
red_coches.compile(optimizer='SGD', loss='categorical_crossentropy',
                   metrics=['categorical_accuracy'])

In [180]:
red_coches.fit(atributos_entrenamiento, objetivo_entrenamiento,
               batch_size=256, epochs=50)

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.4472 - loss: 1.2451
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.4797 - loss: 1.2041
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.5159 - loss: 1.1677
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.5391 - loss: 1.1354
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.5651 - loss: 1.1066
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.5803 - loss: 1.0810
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6042 - loss: 1.0581
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6187 - loss: 1.0376
Epoch 9/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6295 - loss: 1.0192
Epoch 10/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6375 - loss: 1.0025
Epoch 11/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6498 - loss: 0.9874
Epoch 12/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6541 - loss: 0.9736
Epoch 13/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6585 - loss: 0.9610
Epoch 14/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6643 - loss: 0.9493
Epoch 15/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6708 - loss: 0.9386
Epoch 16/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6766 - loss: 0.9285
Epoch 17/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6802 - loss: 0.9192
Epoch 18/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6831 - loss: 0.9104
Epoch 19/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6838 - loss: 0.9021
Epoch 20/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6838 - loss: 0.8943
Epoch 21/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6860 - loss: 0.8868
Epoch 22/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6867 - loss: 0.8797
Epoch 23/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6881 - loss: 0.8730
Epoch 24/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6896 - loss: 0.8665
Epoch 25/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6896 - loss: 0.8602
Epoch 26/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6910 - loss: 0.8542
Epoch 27/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6918 - loss: 0.8484
Epoch 28/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6925 - loss: 0.8428
Epoch 29/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6925 - loss: 0.8374
Epoch 30/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6925 - loss: 0.8321
Epoch 31/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6932 - loss: 0.8269
Epoch 32/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6932 - loss: 0.8219
Epoch 33/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6932 - loss: 0.8171
Epoch 34/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6939 - loss: 0.8123
Epoch 35/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6954 - loss: 0.8077
Epoch 36/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6961 - loss: 0.8032
Epoch 37/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6968 - loss: 0.7987
Epoch 38/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6968 - loss: 0.7944
Epoch 39/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6975 - loss: 0.7901
Epoch 40/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6975 - loss: 0.7860
Epoch 41/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6975 - loss: 0.7819
Epoch 42/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6975 - loss: 0.7778
Epoch 43/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6975 - loss: 0.7739
Epoch 44/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6990 - loss: 0.7700
Epoch 45/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6990 - loss: 0.7662
Epoch 46/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6997 - loss: 0.7624
Epoch 47/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6997 - loss: 0.7587
Epoch 48/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7012 - loss: 0.7551
Epoch 49/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.7012 - loss: 0.7515
Epoch 50/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7012 - loss: 0.7480

In [181]:
red_coches.evaluate(atributos_prueba, objetivo_prueba)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.7370 - loss: 0.7057

[0.7057406306266785, 0.736994206905365]

In [182]:
red_coches = Sequential()
red_coches.add(Input(shape=(21,)))
red_coches.add(Dense(8, activation='relu'))
red_coches.add(Dense(16, activation='relu'))
red_coches.add(Dense(32, activation='relu'))
red_coches.add(Dense(4, activation='softmax'))

In [183]:
red_coches.compile(optimizer='SGD', loss='categorical_crossentropy',
                   metrics=['categorical_accuracy'])

In [184]:
red_coches.fit(atributos_entrenamiento, objetivo_entrenamiento,
               batch_size=32, epochs=50, verbose=False)

In [185]:
red_coches.evaluate(atributos_prueba, objetivo_prueba)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.9133 - loss: 0.2122

[0.21219833195209503, 0.913294792175293]

### Ejercicio 3

Los púlsares son un tipo raro de estrella de neutrones que produce emisiones de radio detectables aquí en la Tierra. Son de considerable interés científico como sondas del espacio-tiempo, el medio interestelar y los estados de la materia.

A medida que los púlsares giran, su haz de emisión recorre el cielo y, cuando cruza nuestra línea de visión, produce un patrón detectable de emisión de radio de banda ancha. Como los púlsares giran rápidamente, este patrón se repite periódicamente. Por tanto, la búsqueda de púlsares implica buscar señales de radio periódicas con grandes radiotelescopios.

Cada púlsar produce un patrón de emisión algo diferente, que varía levemente con cada rotación. Por lo tanto, una detección de señal potencial conocida como «candidata» se promedia a lo largo de muchas rotaciones del púlsar, según lo determinado por la duración de una observación. A falta de información adicional, cada candidato podría describir un púlsar real. Sin embargo, en la práctica, casi todas las detecciones son causadas por interferencias de radiofrecuencia (RFI) y ruido, lo que dificulta encontrar señales legítimas.

El fichero `pulsar_stars.csv` contiene datos acerca de una serie de púlsares reales y de ejemplos espurios producidos por RFI y ruido. Cada candidato se describe mediante ocho atributos continuos extraídos de las señales recibidas.

Se pide construir una red neuronal que permita abordar, con el mayor rendimiento posible, la tarea de determinar si un candidato es o no un púlsar.

### Ejercicio 4

Los [abulones](https://es.wikipedia.org/wiki/Haliotis) son una familia de moluscos gasterópodos. La edad de cada individuo está correlacionada con el número de anillos de su concha y, por tanto, puede determinarse cortando la concha a través del cono, tiñéndola y contando el número de anillos a través de un microscopio. Este procedimiento requiere mucho tiempo y es propenso a errores, por lo que sería preferible poder determinar la edad directamente a partir de medidas físicas más fáciles de obtener.

El fichero `abalone.csv` contiene la siguiente información de distintos individuos de abulones:

* Sexo (`Sex`): atributo discreto con posibles valores `M` (macho), `F` (hembra) e `I` (infante).
* Longitud (`Length`) en milímetros.
* Diámetro (`Diameter`) en milímetros.
* Altura (`Height`) en milímetros.
* Peso total (`Whole_weight`) en gramos.
* Peso sin la concha (`Shucked_weight`) en gramos.
* Peso intestinal (`Viscera_weight`) en gramos.
* Peso de la concha (`Shell_weight`) en gramos.

Se pide construir una red neuronal que permita abordar, con el mayor rendimiento posible, la tarea de predecir el número de anillos (`Rings`) a partir de los atributos anteriores (entonces bastaría sumar 1.5 a ese número de anillos para obtener la edad, en años, del individuo).